channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor

  # optional dependencies
  - xsimd

  # build tools
  - cmake
  - setuptools_scm

  # Python API
  - python
  - xtensor-python

  # run tests
  - catch2
  - numpy

  # build docs
  - doxygen
  - mathjax
